#cloud-config
# Generated by /linux-vm-hardening
# ssh_mode: {{SSH_MODE}}  (public | tailscale)

users:
  - name: {{ADMIN_USERNAME}}
    groups:
      - sudo
      - docker
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: true
    ssh_authorized_keys:
      - {{SSH_PUBLIC_KEY}}

# Disable SSH password auth globally
ssh_pwauth: false

timezone: {{TIMEZONE}}

package_update: true
package_upgrade: true
package_reboot_if_required: false

packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - apt-listchanges
  - curl
  - git

write_files:
  - path: /etc/ssh/sshd_config.d/99-hardening.conf
    permissions: "0644"
    content: |
      # Coolify requires root SSH with key only — never with password
      PermitRootLogin prohibit-password
      PasswordAuthentication no
      PubkeyAuthentication yes
      MaxAuthTries 3
      LoginGraceTime 30
      AllowUsers {{ADMIN_USERNAME}} root
      X11Forwarding no
      AllowTcpForwarding no
      ClientAliveInterval 300
      ClientAliveCountMax 2

  - path: /etc/fail2ban/jail.d/sshd.local
    permissions: "0644"
    content: |
      [sshd]
      enabled = true
      port    = {{SSH_PORT}}
      logpath = %(sshd_log)s
      backend = %(sshd_backend)s
      maxretry = 3
      bantime  = 3600
      findtime = 600
      bantime.increment = true
      bantime.factor = 2
      bantime.maxtime = 604800

  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    permissions: "0644"
    content: |
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
      };
      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::MinimalSteps "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "false";

  - path: /etc/apt/apt.conf.d/20auto-upgrades
    permissions: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

runcmd:
  # Swap 2GB — critical for Coolify on small VMs (cx23 has 4GB RAM)
  - fallocate -l 2G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - echo '/swapfile none swap sw 0 0' >> /etc/fstab
  - echo 'vm.swappiness=10' >> /etc/sysctl.d/99-swap.conf
  - sysctl -p /etc/sysctl.d/99-swap.conf

  # Security services
  - systemctl enable --now fail2ban
  - systemctl enable --now unattended-upgrades
  - systemctl restart sshd

  # Docker — official install script
  - curl -fsSL https://get.docker.com | sh
  - usermod -aG docker {{ADMIN_USERNAME}}
  - systemctl enable --now docker

  # Coolify — DEBIAN_FRONTEND prevents whiptail interactive prompt in headless cloud-init
  - DEBIAN_FRONTEND=noninteractive curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash

  # UFW — regras variam por ssh_mode (substituído abaixo)
  - ufw default deny incoming
  - ufw default allow outgoing
  {{UFW_SSH_RULES}}
  - ufw allow 80/tcp comment "HTTP"
  - ufw allow 443/tcp comment "HTTPS"
  - ufw allow 8000/tcp comment "Coolify UI"
  - ufw allow 6001/tcp comment "Coolify WebSocket"
  - ufw allow 6002/tcp comment "Coolify terminal"
  # Coolify SSHes into host via Docker bridge (docker0 + br-* for custom networks)
  # Regular `ufw allow` does NOT work for this — must go into before.rules
  - |
    sed -i '/^# End required lines/a \
    \
    # Allow Docker containers to reach host SSH (required for Coolify)\
    -A ufw-before-input -i docker0 -p tcp --dport 22 -j ACCEPT\
    -A ufw-before-input -i br-+ -p tcp --dport 22 -j ACCEPT' /etc/ufw/before.rules
  - ufw --force enable

  {{TAILSCALE_INSTALL}}
